.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. machinecoin_qt test_machinecoin_qt
clean: FORCE
	$(MAKE) -C .. machinecoin_qt_clean test_machinecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_machinecoin_qt_check
machinecoin-qt machinecoin-qt.exe: FORCE
	 $(MAKE) -C .. machinecoin_qt
